### ISSUE TITLE
Grant Milestone - PPoGATT support for Android

### ISSUE THREAD

**Issue by crc-32** [pebble-dev/mobile-app#1]
- [x] Determining information (model, colour, etc.) and displaying on pair list (e58b717)
    - [x] Determine info
    - [x] Display on pair list
- [x] Pairing with LE only watch
- [x] ~~PPoGATT client implementation (subscribing to data characteristic to receive packets, writing packets to data characteristic)~~
    - [x] Handling PPoGATT packets and forwarding Pebble protocol data packets to libpebblecommon
    - [x] Write callback for libpebblecommon to send Pebble protocol data packets
- [x] If necessary, logic for pairing with hybrid LE and classic watch
- [x] PPoGATT server implementation (provides service for watch to send packets to / receive packets as a replacement for client mode, avoids all apps seeing PPoGATT activity)
- [x] Validate via pairing a BLE watch from scratch and testing PingPong endpoint ~~in both client and server mode~~.

**Comment by jwise** [comment]
:tada: Grant accepted! The Rebble Alliance will grant $500 on completion of this work. :tada:

**Comment by jwise** [comment]
It sounds to me like a handful of other folks have replicated that it works on their watches, so I agree that this is done!  My understanding is that there are still a few stability things to shake out, but I think this meets what we've agreed on for the grant.  Excellent work!
