### ISSUE TITLE
Grant Milestone: Boot server and app locker sync support

### ISSUE THREAD

**Issue by crc-32** [pebble-dev/mobile-app#207]
- [ ] #46
  - [ ] API models
    - [ ] Boot response
    - [ ] Auth responses
    - [ ] Locker response
  - [ ] Boot support
    - [ ] Support requesting boot config
    - [ ] Use boot response to configure API classes via riverpod providers
  - [ ] Auth support
    - [ ] OAuth flow
      - [ ] Support opening OAuth login url in embedded webview
      - [ ] Support token creation via code grant and PKCE
        - [ ] Handle callback uri and send back to flutter from platform
          - [ ] iOS
          - [ ] Android
    - [ ] Token riverpod provider
    - [ ] Support requesting user profile
  - [ ] Locker sync
    - [ ] Support storing apps from request into locker sync db
    - [ ] Request initial locker on login
    - [ ] Re-sync on an interval
    - [ ] Request removal when app is removed locally
  - [ ] PBW downloading and installation
- [ ] Grant completion validation
  - OAuth flow logs in
  - Locker is contacted (based on boot endpoint config) and adds current apps
  - Apps and watchfaces show on watch and install when opened
  - Removal of app removes from remote locker

**Comment by crc-32** [comment]
Blocked by https://github.com/pebble-dev/rebble-appstore-api/pull/24 and https://github.com/pebble-dev/rebble-boot/pull/12
