### ISSUE TITLE
Grant milestone: UI prototype

### ISSUE THREAD

**Issue by piggehperson** [pebble-dev/mobile-app#43]
I will create a workable UI prototype in Figma that performs all of the listed functions in the milestones below. The figma file is located at https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424

- [ ] Onboard new users
    - [ ] Ask for permissions
    - [x] Pair with a watch
    - [ ] Flash a recovery mode watch with firmware
    - [ ] Set up RWS
    - [x] Setup language
    - [ ] Setup health

- [ ] Core features
    - [x] Manage notification mirroring
        - [x] Silence phone when connected to watch (calls, notifications)
    - [ ] Manage connectivity
        - [x] Pair additional watches
        - [x] Switch connected device
        - [ ] Update device firmware
    - [ ] Manage calendars
    - [ ] Canned messages/favorite contacts in built in SMS app
    - [ ] Analytics optout/in

- [ ] Locker
    - [x] Manage owned watch faces
    - [x] Manage owned watch apps
    - [x] Configure watch apps and faces
    - [ ] Manage permissions for watch apps and faces
    - [x] Install new apps from RWS appstore

- [x] Health
    - [x] Enable and disable the feature
    - [x] Display steps, sleep, and heart rate data
    - [x] Log in/log out of google fit to sync data
    - [x] Manage health database
        - [x] Import
        - [x] Export
        - [x] Delete

- [ ] Support/Community links page
    - [ ] Support email
    - [ ] Share app logs
    - [ ] Discord server
    - [ ] Subreddit

- [ ] Developer features
    - [ ] Connect to a PC running SDK tools
    - [ ] View logs from apps on connected watch
    - [ ] Take screenshot of watch

**Comment by piggehperson** [comment]
This issue has been split into 4 upon acception of grant proposal:
- https://github.com/pebble-dev/mobile-app/issues/48
- https://github.com/pebble-dev/mobile-app/issues/49
- https://github.com/pebble-dev/mobile-app/issues/50
- https://github.com/pebble-dev/mobile-app/issues/51
