### ISSUE TITLE
Grant milestone: UI prototype: Onboard new users + core features

### ISSUE THREAD

**Issue by piggehperson** [pebble-dev/mobile-app#48]
I will create a workable UI prototype in Figma that performs all of the listed functions in the milestones below. The figma file is located at https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424

- [x] Onboard new users
    - [x] Ask for permissions
    - [x] Pair with a watch
        - [x] Bluetooth LE/Bluetooth classic scanning
        - [X] Other pairing methods (manual Bluetooth address entry)
    - [X] Flash a recovery mode watch with firmware
    - [X] Set up RWS
    - [X] Setup language
    - [X] Setup health

- [x] Core features
    - [x] Manage notification mirroring
        - [x] Enable and disable notification mirroring per app
        - [x] Silence phone when connected to watch (calls, notifications)
    - [x] Manage connectivity
        - [x] Pair additional watches
        - [x] Switch connected device
        - [x] Update device firmware
    - [X] Manage calendars
    - [x] Canned messages/favorite contacts in built in SMS app
    - [X] Analytics optout/in

**Comment by matejdro** [comment]
> Manage calendars

Suggestion: We should have "Full resync" button somewhere which would delete and re-sync all timeline pins to the watch (including calendar). Timeline sync is write-only on the watch (e.g. we cannot check what calendar events have or haven't been synced to the watch yet). We will workaround that with storing this data on the phone, but that means that if user is moving watch between different phones, timeline can get out of sync.

**Comment by piggehperson** [comment]
Great suggestion; Is there any drawback to just doing this anytime the calendar updates or on a set interval? Would a full resync add duplicate events on the watch?

**Comment by matejdro** [comment]
No, full resync would delete all data from the watch and then re-sync all calendar events, so this would not create duplicate events. However it would transfer a lot of unnecessary data (every calendar pin would have to be re-transferred on every sync) which I imagine would have an effect on Pebble's battery life.

Do you think there are many people that swap watches between phones? Maybe we could add an option to always use full sync for those if there is high enough need.

**Comment by piggehperson** [comment]
Hm, what about a full resync on connect & maybe at certain intervals (6 hours?) With an option under Settings->calender->advanced  to do a full resync on every change?

**Comment by matejdro** [comment]
As I said, for vast majority of the cases full resync is never needed. It would only be needed if user is swapping same watch between phones.

**Comment by jwise** [comment]
🎉 The Rebble Alliance would be happy to fund this at $750!

**Comment by jwise** [comment]
I think one of my favorite things about this is the style introduced in the updater.  It feels like it not only embraces "the Pebble style", but animates it and humanizes it further with colors to convey the excitement of new functionality (or a watch being restored from the dead).  As always, great work.

I agree that this milestone is complete!  cc: @ishotjr
