### ISSUE TITLE
Grant milestone: UI prototype: Locker

### ISSUE THREAD

**Issue by piggehperson** [pebble-dev/mobile-app#49]
I will create a workable UI prototype in Figma that performs all of the listed functions in the milestones below. The figma file is located at https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424

- [x] Manage owned watch faces
- [x] Manage owned watch apps
- [x] Configure watch apps and faces
- [x] Manage permissions for watch apps and faces
- [x] Install new apps from RWS appstore
    - [x] Search bar and browser controls when necessary (legacy app store)

**Comment by jwise** [comment]
🎉 The Rebble Alliance would be happy to fund this at $400!

**Comment by jwise** [comment]
❤️ I believe that this is done!  cc: @ishotjr 

I *love* the metaphor of stargazing for accessing the internet.  It fits right in with the Rebble (and Pebble) whimsy.
