### ISSUE TITLE
Grant milestone: UI prototype: Health

### ISSUE THREAD

**Issue by piggehperson** [pebble-dev/mobile-app#50]
I will create a workable UI prototype in Figma that performs all of the listed functions in the milestones below. The figma file is located at https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424

- [x] Enable and disable the feature
- [x] Display steps, sleep, and heart rate data
- [x] Log in/log out of google fit to sync data
- [x] Manage health database
    - [x] Import
    - [x] Export
    - [x] Delete

**Comment by jwise** [comment]
🎉 The Rebble Alliance would be happy to fund this at $400!

**Comment by jwise** [comment]
🎉 I agree that this has been completed as specified!  I love the color combinations: they really feel joyful and friendly.  cc: @ishotjr
