### ISSUE TITLE
Grant milestone: UI prototype: Community support and Developer features

### ISSUE THREAD

**Issue by piggehperson** [pebble-dev/mobile-app#51]
I will create a workable UI prototype in Figma that performs all of the listed functions in the milestones below. The figma file is located at https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424

- [X] Support/Community links page
    - [X] Rebble support email
    - [X] Share app logs (moved to Analytics screen)
    - [X] Discord server
    - [X] Subreddit

- [X] Developer features
    - [X] Connect to a PC running SDK tools
    - [X] ~~View logs from apps on connected watch~~ Feature dropped, maybe? I finished the prototype either way
    - [X] Take screenshot of watch

**Comment by jwise** [comment]
🎉 The Rebble Alliance would be happy to fund this at $600!

**Comment by piggehperson** [comment]
I'm giving this issue to @lolrepeatlol, they are doing the work for this and they'll receive the grant payment on completion. Would like to get them added as a collaborator on this repo so they can be assigned to this issue and stuff

**Comment by lolrepeatlol** [comment]
passing this back to @piggehperson bc i realized after working on this and showing my work to actual developers, I was guessing at best and had no idea if what I was doing was actually useful for them.

if anyone still wants to see the work i've previously put into this, you can check https://www.figma.com/file/RlyOPIpd3u2I4kVe6oXIy2/Issue-51?node-id=0%3A1 to see how it turned out (there are two pages, one for community/support links and one for developers).

**Comment by jwise** [comment]
🎉 I agree that this grant milestone is done!  Fantastic work, as always.

cc: @ishotjr
