### ISSUE TITLE
Grant Milestone: Completion of Basics and Apps milestones on Android

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#52]
I will complete tasks in the Basics and Apps milestones that have not been taken by the @crc-32 yet:

# Milestone 1:

- [X] Sync phone time to the watch (https://github.com/pebble-dev/mobile-app/issues/16)
- [x] Calendar sync (https://github.com/pebble-dev/mobile-app/issues/26)
- [x] Music Control (https://github.com/pebble-dev/mobile-app/issues/25)

# Milestone 2:

- [x] App installation fro pbw file (https://github.com/pebble-dev/mobile-app/issues/33)
- [x] Store app locker on the phone (https://github.com/pebble-dev/mobile-app/issues/34 - This task is prerequisite for  both me and @crc-32. We have agreed that whoever needs it first, implements it) 
- [x] Complete PebbleKit Android implementation (https://github.com/pebble-dev/mobile-app/issues/37)
- [x] Add support for Sports and Golf apps (https://github.com/pebble-dev/mobile-app/issues/38)
- [x] Complete developer connection implementation (https://github.com/pebble-dev/mobile-app/issues/47)

- ✖️ Add Data Logging support (https://github.com/pebble-dev/mobile-app/issues/39) WON'T DO

# Limitations

* Everything here applies to Android only. While I will try to implement as much features as possible in flutter, which is shared between Android and iOS, iOS developer will still need to connect all of those features with the iOS.
* This does not include proper UI, since designs are still being done (https://github.com/pebble-dev/mobile-app/issues/43) and to be frank, I need to get some experience with Flutter UI first. As the part of this grant, I will add some rudimentary UI to the app that will allow use of the features, but it will not look or feel good. Proper "fancy" UI can be implemented after the fact.

**Comment by jwise** [comment]
:tada: This grant is approved!  Rebble Alliance will pay $1500 on completion of milestone 1, and $1500 on completion of milestone 2.  This is super exciting -- thanks!

**Comment by jwise** [comment]
This is absolutely amazing.  I agree that milestone 1 is complete!

**Comment by matejdro** [comment]
@jwise I don't think I will be doing the data logging. It is very complicated, there is little documentation and from what I can see, no apps use it anymore. Can you deduct that from my grant, please?

**Comment by jwise** [comment]
Excellent, excellent work.  When I originally estimated Milestone 2, it looks like I included some PBW install work, but it looks like we assumed you might not be doing the app locker storage work -- but you did end up doing that after all.  So I'm happy to call it even at the originally agreed $1,500.  I agree that Milestone 2 is complete!

**Comment by jwise** [comment]
cc: @ishotjr !
