### ISSUE TITLE
Grant milestone: Setup UI for Cobble

### ISSUE THREAD

**Issue by lolrepeatlol** [pebble-dev/mobile-app#91]
I will make a UI prototype for setup/new user onboarding that performs all the functions listed below. Latest Figma document, _a mix of what I thought was the best of my work and Lav's work_, available to view here: ~~https://www.figma.com/file/fwIWPY9SkkYhtzVhV9EsmN/Rebble-Setup-Mixed?node-id=0%3A1~~ 
latest file compact: https://www.figma.com/file/d46mpJXu9sE6LSyM9ioJi4/Rebble-Setup-v8-Compact?node-id=0%3A1 
latest file separated: https://www.figma.com/file/C2iwNTF4945qDAjo8PFUx2/Rebble-Setup-v8-Separated?node-id=0%3A1

(the last file with all of my work seen here https://www.figma.com/file/aezGKFps6Odrv3HjtA0xIq/Rebble-Setup-v5?node-id=0%3A1)
(file with all of Lav's work seen here https://www.figma.com/file/mXl0svBSnlGV2MKfTj8H7e/Mobile-app?node-id=121%3A424, her proposal seen in #48)

* [x] Allows setup skipping
* [x] Pairing
   * [x] Pair with a device by asking for location, classic style
   * [x] Pair with a device via manual BT address, hidden
   * [x] Connect to emulator, hidden
* [x] Updates
   * [x] Check for updates
   * [x] Install/skip updates **_(some ideas from Lav in #48, but executed by me a bit differently)_**
   * [x] Update installation confirmation
* [x] ~~Changes OS to/from Rebble OS~~ (removed upon request b/c don't want users to complain)
   * [x] ~~Hidden option to change OS to Rebble OS with a lot of disclaimers~~
   * [x] ~~Change OS to Pebble OS~~
   * [x] ~~Confirmation for both OS changes~~
* [x] ~~Manually choose OS file to flash with the system file picker, hidden~~ (removed upon request b/c don't want users to complain)
* [x] Setup Pebble/Rebble Health
   * [x] Ask for whether Health should be on/off **_(some work here done by Lav in #48)_**
   * [x] Ask for daily summary permission for steps/sleep **_(some work here done by Lav in #48)_**
   * [x] Set up Apple Health/Google Fit sync **_(some work here done by Lav in #48)_**
   * [x] Ask for person's general Health information like their age, sex, height, weight, in metric and imperial
* [x] Ask for permissions
   * [x] Compact style
   * [x] Separated style
   * [x] Tell user consequences of disabling permissions **_(idea suggested by Lav, but executed by me differently)_**
* [x] Setup language 
   * [x] Ask for dictation language
* [x] Sign in to Rebble Web Services **_(most work here done by Lav in #48)_**
* [x] Welcome user to new app
   * [x] Opt out of anonymized analytics
* [ ] Appearance
   * [ ] Light mode
   * [x] Dark mode

Because a chunk of this work was taken from Lavender where I thought necessary, Lavender absolutely deserves a split of the Grant if this proposal is accepted.
